
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "enparto"
version = "0.1.0"
description = ""
authors = [{ name = "Maximilian Lackner", email = "maximilian@s4e.at" }, {name = "Fabian Kovac", email = "fabian.kovac@ustp.at"}]
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]

[tool.black]
line-length = 88
target-version = ['py39']